create database Child_Growth_Tracking_System;
Drop database  Child_Growth_Tracking_System;

Use Child_Growth_Tracking_System;

Drop table Users;
CREATE TABLE Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,  -- ID người dùng, tự động tăng
  Username VARCHAR(50) NOT NULL UNIQUE,   -- Tên đăng nhập (duy nhất, không rỗng)
  PasswordHash VARCHAR(255) NOT NULL,     -- Mật khẩu đã mã hóa
  Email VARCHAR(100) NOT NULL UNIQUE,     -- Email người dùng (duy nhất)
  FullName VARCHAR(100) NOT NULL,         -- Họ và tên đầy đủ
  RoleName ENUM('Admin', 'Doctor', 'User') NOT NULL, -- Vai trò của người dùng (Admin, Doctor, User)
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP -- Ngày tạo tài khoản
);
-- Mẫu 1: Tài khoản Admin
INSERT INTO Users (Username, PasswordHash, Email, FullName, RoleName)
VALUES 
-- 5 admin
('Admin_1', 'Dat888', 'Ledat@gmail.com', 'Lê Thanh Đạt ', 'Admin'),
('Admin_2', 'Kha222', 'Khatran@gmail.com', 'Trần Chí Kha ', 'Admin'),
('Admin_3', 'Vu333', 'Vudong@gmail.com', 'Đồng Huy Vũ ', 'Admin'),
('Admin_4', 'Dam444', 'Dampha@gmail.com', 'Phạm Lã Quang Đam ', 'Admin'),
('Admin_5', 'Hung555', 'Hungnguyen@gmail.com', 'Nguyễn Tuấn Hùng ', 'Admin'),  
-- 50 docters
('Doctor_1', 'Lan578', 'lanvo.doctor@gmail.com', 'Võ Thị Lan', 'Doctor'),
('Doctor_2', 'Hoa924', 'hoale.doctor@gmail.com', 'Lê Thị Hoa', 'Doctor'),
('Doctor_3', 'Minh367', 'minhpham.doctor@gmail.com', 'Phạm Minh', 'Doctor'),
('Doctor_4', 'Anh452', 'anhduong.doctor@gmail.com', 'Dương Tuấn Anh', 'Doctor'),
('Doctor_5', 'Trang819', 'trangphan.doctor@gmail.com', 'Phan Thị Trang', 'Doctor'),
('Doctor_6', 'Hung635', 'hungdao.doctor@gmail.com', 'Đào Văn Hùng', 'Doctor'),
('Doctor_7', 'Thao294', 'thaonguyen.doctor@gmail.com', 'Nguyễn Thị Thảo', 'Doctor'),
('Doctor_8', 'Dat781', 'dathoang.doctor@gmail.com', 'Hoàng Tiến Đạt', 'Doctor'),
('Doctor_9', 'Linh436', 'linhle.doctor@gmail.com', 'Lê Thị Linh', 'Doctor'),
('Doctor_10', 'Quan592', 'quantran.doctor@gmail.com', 'Trần Minh Quân', 'Doctor'),
('Doctor_11', 'Mai847', 'maivu.doctor@gmail.com', 'Vũ Thị Mai', 'Doctor'),
('Doctor_12', 'Tuan183', 'tuanbui.doctor@gmail.com', 'Bùi Văn Tuấn', 'Doctor'),
('Doctor_13', 'Huong759', 'huongdinh.doctor@gmail.com', 'Đinh Thị Hương', 'Doctor'),
('Doctor_14', 'Son264', 'sonngo.doctor@gmail.com', 'Ngô Văn Sơn', 'Doctor'),
('Doctor_15', 'Hien391', 'hienpham.doctor@gmail.com', 'Phạm Thị Hiền', 'Doctor'),
('Doctor_16', 'Duc648', 'ducnguyen.doctor@gmail.com', 'Nguyễn Đức', 'Doctor'),
('Doctor_17', 'Yen523', 'yentran.doctor@gmail.com', 'Trần Thị Yến', 'Doctor'),
('Doctor_18', 'Cuong976', 'cuongdo.doctor@gmail.com', 'Đỗ Mạnh Cường', 'Doctor'),
('Doctor_19', 'Nga145', 'ngado.doctor@gmail.com', 'Đỗ Thị Nga', 'Doctor'),
('Doctor_20', 'Thanh832', 'thanhle.doctor@gmail.com', 'Lê Công Thành', 'Doctor'),
('Doctor_21', 'Hanh679', 'hanhvu.doctor@gmail.com', 'Vũ Thị Hạnh', 'Doctor'),
('Doctor_22', 'Khanh214', 'khanhhoang.doctor@gmail.com', 'Hoàng Gia Khánh', 'Doctor'),
('Doctor_23', 'Hong567', 'hongdang.doctor@gmail.com', 'Đặng Thị Hồng', 'Doctor'),
('Doctor_24', 'Truong938', 'truongphan.doctor@gmail.com', 'Phan Văn Trường', 'Doctor'),
('Doctor_25', 'Chi475', 'chinguyen.doctor@gmail.com', 'Nguyễn Thị Chi', 'Doctor'),
('Doctor_26', 'Binh721', 'binhtrinh.doctor@gmail.com', 'Trịnh Văn Bình', 'Doctor'),
('Doctor_27', 'Nhung386', 'nhungpham.doctor@gmail.com', 'Phạm Thị Nhung', 'Doctor'),
('Doctor_28', 'Long549', 'longvo.doctor@gmail.com', 'Võ Thành Long', 'Doctor'),
('Doctor_29', 'Thu917', 'thuly.doctor@gmail.com', 'Lý Thị Thu', 'Doctor'),
('Doctor_30', 'Dung283', 'dungtran.doctor@gmail.com', 'Trần Văn Dũng', 'Doctor'),
('Doctor_31', 'Phuong654', 'phuongdoan.doctor@gmail.com', 'Đoàn Thị Phương', 'Doctor'),
('Doctor_32', 'Vinh429', 'vinhle.doctor@gmail.com', 'Lê Quang Vinh', 'Doctor'),
('Doctor_33', 'Van875', 'vanthai.doctor@gmail.com', 'Thái Thị Vân', 'Doctor'),
('Doctor_34', 'Hoang192', 'hoangdao.doctor@gmail.com', 'Đào Minh Hoàng', 'Doctor'),
('Doctor_35', 'Giang637', 'giangnguyen.doctor@gmail.com', 'Nguyễn Thị Giang', 'Doctor'),
('Doctor_36', 'Phong528', 'phongtran.doctor@gmail.com', 'Trần Đình Phong', 'Doctor'),
('Doctor_37', 'Diep941', 'diepvu.doctor@gmail.com', 'Vũ Thị Diệp', 'Doctor'),
('Doctor_38', 'Manh362', 'manhhoang.doctor@gmail.com', 'Hoàng Đức Mạnh', 'Doctor'),
('Doctor_39', 'Tuyet715', 'tuyetdo.doctor@gmail.com', 'Đỗ Thị Tuyết', 'Doctor'),
('Doctor_40', 'Trung483', 'trungnguyen.doctor@gmail.com', 'Nguyễn Văn Trung', 'Doctor'),
('Doctor_41', 'My926', 'myvo.doctor@gmail.com', 'Võ Thị Mỹ', 'Doctor'),
('Doctor_42', 'Quoc571', 'quoctran.doctor@gmail.com', 'Trần Quốc', 'Doctor'),
('Doctor_43', 'Nhu384', 'nhupham.doctor@gmail.com', 'Phạm Thị Như', 'Doctor'),
('Doctor_44', 'Hai749', 'hainguyen.doctor@gmail.com', 'Nguyễn Văn Hải', 'Doctor'),
('Doctor_45', 'Bich235', 'bichle.doctor@gmail.com', 'Lê Thị Bích', 'Doctor'),
('Doctor_46', 'Nam682', 'namdinh.doctor@gmail.com', 'Đinh Văn Nam', 'Doctor'),
('Doctor_47', 'Loan497', 'loantran.doctor@gmail.com', 'Trần Thị Loan', 'Doctor'),
('Doctor_48', 'Tien853', 'tienhoang.doctor@gmail.com', 'Hoàng Minh Tiến', 'Doctor'),
('Doctor_49', 'Huyen621', 'huyenpham.doctor@gmail.com', 'Phạm Thị Huyền', 'Doctor'),
('Doctor_50', 'Quang394', 'quangvu.doctor@gmail.com', 'Vũ Đình Quang', 'Doctor'),
-- 400 Users
('User_1', 'Tuan578', 'NguyenVanTuan@gmail.com', 'Nguyễn Văn Tuấn', 'User'),
('User_2', 'Mai924', 'LeThiMai@gmail.com', 'Lê Thị Mai', 'User'),
('User_3', 'Hung367', 'PhamVanHung@gmail.com', 'Phạm Văn Hùng', 'User'),
('User_4', 'Lan452', 'DuongThiLan@gmail.com', 'Dương Thị Lan', 'User'),
('User_5', 'Minh819', 'PhanVanMinh@gmail.com', 'Phan Văn Minh', 'User'),
('User_6', 'Hoa635', 'DaoThiHoa@gmail.com', 'Đào Thị Hoa', 'User'),
('User_7', 'Nam294', 'NguyenVanNam@gmail.com', 'Nguyễn Văn Nam', 'User'),
('User_8', 'Linh781', 'HoangThiLinh@gmail.com', 'Hoang Thị Linh', 'User'),
('User_9', 'Duc436', 'LeVanDuc@gmail.com', 'Lê Văn Đức', 'User'),
('User_10', 'Nga592', 'TranThiNga@gmail.com', 'Trần Thị Nga', 'User'),
('User_11', 'Son847', 'VuVanSon@gmail.com', 'Vũ Văn Sơn', 'User'),
('User_12', 'Huong183', 'BuiThiHuong@gmail.com', 'Bùi Thị Hương', 'User'),
('User_13', 'Thanh759', 'DinhVanThanh@gmail.com', 'Đinh Văn Thành', 'User'),
('User_14', 'Hong264', 'NgoThiHong@gmail.com', 'Ngô Thị Hồng', 'User'),
('User_15', 'Long391', 'PhamVanTam@gmail.com', 'Phạm Văn Tám', 'User'),
('User_16', 'Van648', 'NguyenThiVan@gmail.com', 'Nguyễn Thị Vân', 'User'),
('User_17', 'Binh523', 'TranVanBinh@gmail.com', 'Trần Văn Bình', 'User'),
('User_18', 'Thu976', 'DoThiThu@gmail.com', 'Đỗ Thị Thu', 'User'),
('User_19', 'Manh145', 'DoManh@gmail.com', 'Đỗ Mạnh', 'User'),
('User_20', 'Nhung832', 'LeThiNhung@gmail.com', 'Lê Thị Nhung', 'User'),
('User_21', 'Quang679', 'VuVanQuang@gmail.com', 'Vũ Văn Quang', 'User'),
('User_22', 'Trang214', 'HoangThiTrang@gmail.com', 'Hoang Thị Trang', 'User'),
('User_23', 'Dat567', 'DangVanDat@gmail.com', 'Đặng Văn Đạt', 'User'),
('User_24', 'Anh938', 'PhanThiAnh@gmail.com', 'Phan Thị Anh', 'User'),
('User_25', 'Dung475', 'NguyenVanDung@gmail.com', 'Nguyễn Văn Dũng', 'User'),
('User_26', 'Hanh721', 'TrinhThiHanh@gmail.com', 'Trịnh Thị Hạnh', 'User'),
('User_27', 'Vin386', 'PhamVanVin@gmail.com', 'Phạm Văn Vin', 'User'),
('User_28', 'My549', 'VoThiMy@gmail.com', 'Võ Thị Mỹ', 'User'),
('User_29', 'Trung917', 'LyVanTrung@gmail.com', 'Lý Văn Trung', 'User'),
('User_30', 'Chi283', 'TranThiChi@gmail.com', 'Trần Thị Chi', 'User'),
('User_31', 'Hoang654', 'DoanVanHoang@gmail.com', 'Đoàn Văn Hoàng', 'User'),
('User_32', 'Yen429', 'LeThiYen@gmail.com', 'Lê Thị Yến', 'User'),
('User_33', 'Tien875', 'ThaiVanTien@gmail.com', 'Thái Văn Tiến', 'User'),
('User_34', 'Phuong192', 'DaoThiPhuong@gmail.com', 'Đào Thị Phương', 'User'),
('User_35', 'Quan637', 'NguyenVanQuan@gmail.com', 'Nguyễn Văn Quân', 'User'),
('User_36', 'Bich528', 'TranThiBich@gmail.com', 'Trần Thị Bích', 'User'),
('User_37', 'Hai941', 'VuVanHai@gmail.com', 'Vũ Văn Hải', 'User'),
('User_38', 'Huyen362', 'HoangThiHuyen@gmail.com', 'Hoang Thị Huyền', 'User'),
('User_39', 'Cuong715', 'DoVanCuong@gmail.com', 'Đỗ Văn Cường', 'User'),
('User_40', 'Giang483', 'NguyenThiGiang@gmail.com', 'Nguyễn Thị Giang', 'User'),
('User_41', 'Phong926', 'VoVanPhong@gmail.com', 'Võ Văn Phong', 'User'),
('User_42', 'Tuyet571', 'TranThiTuyet@gmail.com', 'Trần Thị Tuyết', 'User'),
('User_43', 'Diep384', 'PhamThiDiep@gmail.com', 'Phạm Thị Diệp', 'User'),
('User_44', 'Quoc749', 'NguyenQuoc@gmail.com', 'Nguyễn Quốc', 'User'),
('User_45', 'Nhu235', 'LeThiNhu@gmail.com', 'Lê Thị Như', 'User'),
('User_46', 'Loan682', 'DinhThiLoan@gmail.com', 'Đinh Thị Loan', 'User'),
('User_47', 'Khanh497', 'TranGiaKhanh@gmail.com', 'Trần Gia Khánh', 'User'),
('User_48', 'Truong853', 'HoangVanTruong@gmail.com', 'Hoang Văn Trường', 'User'),
('User_49', 'Thao621', 'PhamThiThao@gmail.com', 'Phạm Thị Thảo', 'User'),
('User_50', 'Tam394', 'VuThiTam@gmail.com', 'Vũ Thị Tam', 'User'),
('User_51', 'Tuan167', 'PhamVanTuan@gmail.com', 'Phạm Văn Tuấn', 'User'),
('User_52', 'Mai283', 'TranThiMai@gmail.com', 'Trần Thị Mai', 'User'),
('User_53', 'Hung495', 'VoVanHung@gmail.com', 'Võ Văn Hùng', 'User'),
('User_54', 'Lan712', 'NguyenThiLan@gmail.com', 'Nguyễn Thị Lan', 'User'),
('User_55', 'Minh846', 'DoVanMinh@gmail.com', 'Đỗ Văn Minh', 'User'),
('User_56', 'Hoa359', 'LeThiHoa@gmail.com', 'Lê Thị Hoa', 'User'),
('User_57', 'Nam624', 'DinhVanNam@gmail.com', 'Đinh Văn Nam', 'User'),
('User_58', 'Linh937', 'PhanThiLinh@gmail.com', 'Phan Thị Linh', 'User'),
('User_59', 'Duc185', 'HoangVanDuc@gmail.com', 'Hoang Văn Đức', 'User'),
('User_60', 'Nga472', 'DaoThiNga@gmail.com', 'Đào Thị Nga', 'User'),
('User_61', 'Son813', 'NguyenVanSon@gmail.com', 'Nguyễn Văn Sơn', 'User'),
('User_62', 'Huong256', 'TranThiHuong@gmail.com', 'Trần Thị Hương', 'User'),
('User_63', 'Thanh695', 'VuVanThanh@gmail.com', 'Vũ Văn Thành', 'User'),
('User_64', 'Hong342', 'TrinhThiHong@gmail.com', 'Trịnh Thị Hồng', 'User'),
('User_65', 'Long578', 'NgoVanLong@gmail.com', 'Ngô Văn Long', 'User'),
('User_66', 'Van891', 'PhamThiVan@gmail.com', 'Phạm Thị Vân', 'User'),
('User_67', 'Binh237', 'LeVanBinh@gmail.com', 'Lê Văn Bình', 'User'),
('User_68', 'Thu625', 'HoangThiThu@gmail.com', 'Hoang Thị Thu', 'User'),
('User_69', 'Manh943', 'TranManh@gmail.com', 'Trần Mạnh', 'User'),
('User_70', 'Nhung361', 'DaoThiNhung@gmail.com', 'Đào Thị Nhung', 'User'),
('User_71', 'Quang728', 'DuongVanQuang@gmail.com', 'Dương Văn Quang', 'User'),
('User_72', 'Trang194', 'NguyenThiTrang@gmail.com', 'Nguyễn Thị Trang', 'User'),
('User_73', 'Dat537', 'VoVanDat@gmail.com', 'Võ Văn Đạt', 'User'),
('User_74', 'Anh862', 'LeThiAnh@gmail.com', 'Lê Thị Anh', 'User'),
('User_75', 'Dung295', 'PhamVanDung@gmail.com', 'Phạm Văn Dũng', 'User'),
('User_76', 'Hanh614', 'HoangThiHanh@gmail.com', 'Hoang Thị Hạnh', 'User'),
('User_77', 'Vinh938', 'TranVanVinh@gmail.com', 'Trần Văn Vinh', 'User'),
('User_78', 'My467', 'NguyenThiMy@gmail.com', 'Nguyễn Thị Mỹ', 'User'),
('User_79', 'Trung839', 'DinhVanTrung@gmail.com', 'Đinh Văn Trung', 'User'),
('User_80', 'Chi215', 'VoThiChi@gmail.com', 'Võ Thị Chi', 'User'),
('User_81', 'Hoang573', 'LeVanHoang@gmail.com', 'Lê Văn Hoàng', 'User'),
('User_82', 'Yen896', 'DoThiYen@gmail.com', 'Đỗ Thị Yến', 'User'),
('User_83', 'Tien312', 'NguyenVanTien@gmail.com', 'Nguyễn Văn Tiến', 'User'),
('User_84', 'Phuong647', 'TranThiPhuong@gmail.com', 'Trần Thị Phương', 'User'),
('User_85', 'Quan982', 'VuongVanQuan@gmail.com', 'Vương Văn Quân', 'User'),
('User_86', 'Bich419', 'DaoThiBich@gmail.com', 'Đào Thị Bích', 'User'),
('User_87', 'Hai756', 'NhatVanHai@gmail.com', 'Nhật Văn Hải', 'User'),
('User_88', 'Huyen293', 'CuuThiHuyen@gmail.com', 'Cửu Thị Huyền', 'User'),
('User_89', 'Cuong524', 'NguyenVanCuong@gmail.com', 'Nguyễn Văn Cường', 'User'),
('User_90', 'Giang871', 'HoangThiGiang@gmail.com', 'Hoang Thị Giang', 'User'),
('User_91', 'Bom245', 'TranVanBom@gmail.com', 'Trần Văn Bom', 'User'),
('User_92', 'Tuyet682', 'PhamThiTuyet@gmail.com', 'Phạm Thị Tuyết', 'User'),
('User_93', 'Diep917', 'VuThiDiep@gmail.com', 'Vũ Thị Diệp', 'User'),
('User_94', 'Quoc358', 'LeQuoc@gmail.com', 'Lê Quốc', 'User'),
('User_95', 'Nhu674', 'NguyenThiNhu@gmail.com', 'Nguyễn Thị Như', 'User'),
('User_96', 'Loan931', 'TrinhThiLoan@gmail.com', 'Trịnh Thị Loan', 'User'),
('User_97', 'Khanh264', 'DoGiaKhanh@gmail.com', 'Đỗ Gia Khánh', 'User'),
('User_98', 'Truong587', 'VuVanTruong@gmail.com', 'Vũ Văn Trường', 'User'),
('User_99', 'Thao942', 'LeThiThao@gmail.com', 'Lê Thị Thảo', 'User'),
('User_100', 'Hien385', 'NguyenThiHien@gmail.com', 'Nguyễn Thị Hiền', 'User'),
('User_101', 'An735', 'PhamVanAn@gmail.com', 'Phạm Văn An', 'User'),
('User_102', 'Lien216', 'TranThiLien@gmail.com', 'Trần Thị Liên', 'User'),
('User_103', 'Danh593', 'VoVanDanh@gmail.com', 'Võ Văn Danh', 'User'),
('User_104', 'Hau847', 'DangThiHau@gmail.com', 'Đặng Thị Hậu', 'User'),
('User_105', 'Tri329', 'NguyenTri@gmail.com', 'Nguyễn Trí', 'User'),
('User_106', 'Kim625', 'LeThiKim@gmail.com', 'Lê Thị Kim', 'User'),
('User_107', 'Tho971', 'DinhVanTho@gmail.com', 'Đinh Văn Thọ', 'User'),
('User_108', 'Chau347', 'PhanThiChau@gmail.com', 'Phan Thị Châu', 'User'),
('User_109', 'Duy682', 'DoVanDuy@gmail.com', 'Đỗ Văn Duy', 'User'),
('User_110', 'Xuan926', 'TranThiXuan@gmail.com', 'Trần Thị Xuân', 'User'),
('User_111', 'Thinh514', 'PhamVanThinh@gmail.com', 'Phạm Văn Thịnh', 'User'),
('User_112', 'Ly863', 'LeThiLy@gmail.com', 'Lê Thị Ly', 'User'),
('User_113', 'Nghia259', 'NguyenVanNghia@gmail.com', 'Nguyễn Văn Nghĩa', 'User'),
('User_114', 'Diem794', 'VuThiDiem@gmail.com', 'Vũ Thị Diễm', 'User'),
('User_115', 'Khoa381', 'TranKhoa@gmail.com', 'Trần Khoa', 'User'),
('User_116', 'Suong652', 'DinhThiSuong@gmail.com', 'Đinh Thị Sương', 'User'),
('User_117', 'Cong973', 'PhamVanCong@gmail.com', 'Phạm Văn Công', 'User'),
('User_118', 'Ha417', 'NguyenThiHa@gmail.com', 'Nguyễn Thị Hà', 'User'),
('User_119', 'Lam769', 'VoVanLam@gmail.com', 'Võ Văn Lâm', 'User'),
('User_120', 'Hien328', 'DangThiHien@gmail.com', 'Đặng Thị Hiên', 'User'),
('User_121', 'Phu574', 'LeVanPhu@gmail.com', 'Lê Văn Phú', 'User'),
('User_122', 'Cam896', 'TranThiCam@gmail.com', 'Trần Thị Cẩm', 'User'),
('User_123', 'Dang251', 'DoVanDang@gmail.com', 'Đỗ Văn Đăng', 'User'),
('User_124', 'Trinh735', 'PhanThiTrinh@gmail.com', 'Phan Thị Trinh', 'User'),
('User_125', 'Duan489', 'NguyenDuan@gmail.com', 'Nguyễn Duẩn', 'User'),
('User_126', 'Le826', 'VuThiLe@gmail.com', 'Vũ Thị Lệ', 'User'),
('User_127', 'Luan352', 'TranVanLuan@gmail.com', 'Trần Văn Luân', 'User'),
('User_128', 'Hang719', 'DinhThiHang@gmail.com', 'Đinh Thị Hằng', 'User'),
('User_129', 'Sinh943', 'LeVanSinh@gmail.com', 'Lê Văn Sinh', 'User'),
('User_130', 'Hue267', 'NguyenThiHue@gmail.com', 'Nguyễn Thị Huệ', 'User'),
('User_131', 'Quy582', 'PhamVanQuy@gmail.com', 'Phạm Văn Quý', 'User'),
('User_132', 'Dong917', 'DangVanDong@gmail.com', 'Đặng Văn Đông', 'User'),
('User_133', 'Bach354', 'TranThiBach@gmail.com', 'Trần Thị Bạch', 'User'),
('User_134', 'Vu673', 'DoVanVu@gmail.com', 'Đỗ Văn Vũ', 'User'),
('User_135', 'Oanh926', 'LeThiOanh@gmail.com', 'Lê Thị Oanh', 'User'),
('User_136', 'Loc419', 'TrinhVanLoc@gmail.com', 'Trịnh Văn Lộc', 'User'),
('User_137', 'Tam758', 'PhamThiTam@gmail.com', 'Phạm Thị Tâm', 'User'),
('User_138', 'Can291', 'NguyenVanCan@gmail.com', 'Nguyễn Văn Cần', 'User'),
('User_139', 'Tien547', 'VoThiTien@gmail.com', 'Võ Thị Tiên', 'User'),
('User_140', 'Trong862', 'TranVanTrong@gmail.com', 'Trần Văn Trọng', 'User'),
('User_141', 'Uyen243', 'LeThiUyen@gmail.com', 'Lê Thị Uyên', 'User'),
('User_142', 'Ung679', 'DaoVanUng@gmail.com', 'Đào Văn Ưng', 'User'),
('User_143', 'Quyen915', 'PhamThiQuyen@gmail.com', 'Phạm Thị Quyên', 'User'),
('User_144', 'Hiep372', 'NguyenVanHiep@gmail.com', 'Nguyễn Văn Hiệp', 'User'),
('User_145', 'Chung697', 'DangThiChung@gmail.com', 'Đặng Thị Chung', 'User'),
('User_146', 'Thai436', 'VoVanThai@gmail.com', 'Võ Văn Thái', 'User'),
('User_147', 'Quynh872', 'TranThiQuynh@gmail.com', 'Trần Thị Quỳnh', 'User'),
('User_148', 'Khoi293', 'PhamVanKhoi@gmail.com', 'Phạm Văn Khôi', 'User'),
('User_149', 'Thuy526', 'NguyenThiThuy@gmail.com', 'Nguyễn Thị Thúy', 'User'),
('User_150', 'Ba819', 'LeVanBa@gmail.com', 'Lê Văn Ba', 'User'),
('User_151', 'Vy265', 'HoangThiVy@gmail.com', 'Hoang Thị Vy', 'User'),
('User_152', 'Tu593', 'TranVanTu@gmail.com', 'Trần Văn Tú', 'User'),
('User_153', 'Ngoc847', 'PhamThiNgoc@gmail.com', 'Phạm Thị Ngọc', 'User'),
('User_154', 'Minh329', 'NguyenMinh@gmail.com', 'Nguyễn Minh', 'User'),
('User_155', 'Luu674', 'DoVanLuu@gmail.com', 'Đỗ Văn Lưu', 'User'),
('User_156', 'Ngan913', 'LeThiNgan@gmail.com', 'Lê Thị Ngân', 'User'),
('User_157', 'Phat345', 'LePhat@gmail.com', 'Lê Phát', 'User'),
('User_158', 'Hoa782', 'NguyenThiHoa@gmail.com', 'Nguyễn Thị Hoa', 'User'),
('User_159', 'Dan429', 'PhamDan@gmail.com', 'Phạm Đan', 'User'),
('User_160', 'Thuy687', 'TranThuy@gmail.com', 'Trần Thúy', 'User'),
('User_161', 'Bao254', 'VoBao@gmail.com', 'Võ Bảo', 'User'),
('User_162', 'My673', 'DoMy@gmail.com', 'Đỗ Mỹ', 'User'),
('User_163', 'Thang915', 'LeThang@gmail.com', 'Lê Thắng', 'User'),
('User_164', 'Hieu462', 'NguyenHieu@gmail.com', 'Nguyễn Hiếu', 'User'),
('User_165', 'Xuan794', 'PhamXuan@gmail.com', 'Phạm Xuân', 'User'),
('User_166', 'Nhi231', 'TranThiNhi@gmail.com', 'Trần Thị Nhi', 'User'),
('User_167', 'Sang587', 'VoVanSang@gmail.com', 'Võ Văn Sang', 'User'),
('User_168', 'Trinh815', 'LeThiTrinh@gmail.com', 'Lê Thị Trinh', 'User'),
('User_169', 'Si369', 'NguyenVanSi@gmail.com', 'Nguyễn Văn Sĩ', 'User'),
('User_170', 'Thanh726', 'PhamThiThanh@gmail.com', 'Phạm Thị Thanh', 'User'),
('User_171', 'Loc194', 'TranVanLoc@gmail.com', 'Trần Văn Lộc', 'User'),
('User_172', 'Huyen473', 'DoThiHuyen@gmail.com', 'Đỗ Thị Huyền', 'User'),
('User_173', 'Tham816', 'LeVanTham@gmail.com', 'Lê Văn Thắm', 'User'),
('User_174', 'Hanh254', 'NguyenThiHanh@gmail.com', 'Nguyễn Thị Hạnh', 'User'),
('User_175', 'Duong635', 'PhamVanDuong@gmail.com', 'Phạm Văn Dương', 'User'),
('User_176', 'Tuyen912', 'VoThiTuyen@gmail.com', 'Võ Thị Tuyền', 'User'),
('User_177', 'Quyen385', 'TranVanQuyen@gmail.com', 'Trần Văn Quyến', 'User'),
('User_178', 'Oanh762', 'DoThiOanh@gmail.com', 'Đỗ Thị Oanh', 'User'),
('User_179', 'Dong253', 'LeVanDong@gmail.com', 'Lê Văn Đông', 'User'),
('User_180', 'Hanh574', 'NguyenThiHanh234@gmail.com', 'Nguyễn Thị Hạnh', 'User'),
('User_181', 'Vinh816', 'PhamVanVinh@gmail.com', 'Phạm Văn Vinh', 'User'),
('User_182', 'Thu273', 'TranThiThu@gmail.com', 'Trần Thị Thu', 'User'),
('User_183', 'Bang592', 'VoVanBang@gmail.com', 'Võ Văn Bằng', 'User'),
('User_184', 'Lien847', 'DoThiLien@gmail.com', 'Đỗ Thị Liên', 'User'),
('User_185', 'Ky329', 'LeVanKy@gmail.com', 'Lê Văn Kỳ', 'User'),
('User_186', 'Tuong651', 'NguyenTuong@gmail.com', 'Nguyễn Tường', 'User'),
('User_187', 'Cam928', 'PhamThiCam@gmail.com', 'Phạm Thị Cẩm', 'User'),
('User_188', 'Duong315', 'TranDuong@gmail.com', 'Trần Dương', 'User'),
('User_189', 'Nguyet743', 'VoThiNguyet@gmail.com', 'Võ Thị Nguyệt', 'User'),
('User_190', 'Phung267', 'DoPhung@gmail.com', 'Đỗ Phụng', 'User'),
('User_191', 'Nhan584', 'NguyenNhan@gmail.com', 'Nguyễn Nhàn', 'User'),
('User_192', 'Kien926', 'LeKien@gmail.com', 'Lê Kiên', 'User'),
('User_193', 'Phi372', 'PhamPhi@gmail.com', 'Phạm Phi', 'User'),
('User_194', 'Huong716', 'TranThiHuong194@gmail.com', 'Trần Thị Hương', 'User'),
('User_195', 'Tra298', 'VoTra@gmail.com', 'Võ Trà', 'User'),
('User_196', 'Tram641', 'DoThiTram@gmail.com', 'Đỗ Thị Trâm', 'User'),
('User_197', 'Hoai923', 'LeHoai@gmail.com', 'Lê Hoài', 'User'),
('User_198', 'Bao517', 'NguyenBao@gmail.com', 'Nguyễn Bảo', 'User'),
('User_199', 'Viet862', 'PhamViet@gmail.com', 'Phạm Việt', 'User'),
('User_200', 'Yen349', 'TranThiYen@gmail.com', 'Trần Thị Yến', 'User'),
('User_201', 'Phuc725', 'VoPhuc@gmail.com', 'Võ Phúc', 'User'),
('User_202', 'Ly196', 'DoThiLy@gmail.com', 'Đỗ Thị Ly', 'User'),
('User_203', 'Hau543', 'LeHau@gmail.com', 'Lê Hậu', 'User'),
('User_204', 'My874', 'NguyenThiMy204@gmail.com', 'Nguyễn Thị Mỹ', 'User'),
('User_205', 'Tu316', 'PhamTu@gmail.com', 'Phạm Tú', 'User'),
('User_206', 'Chau659', 'TranThiChau@gmail.com', 'Trần Thị Châu', 'User'),
('User_207', 'Hung742', 'NguyenVanHung@gmail.com', 'Nguyễn Văn Hùng', 'User'),
('User_208', 'Lan195', 'LeThiLan@gmail.com', 'Lê Thị Lan', 'User'),
('User_209', 'Cao483', 'PhamVanCao@gmail.com', 'Phạm Văn Cao', 'User'),
('User_210', 'Hoa927', 'DoThiHoa@gmail.com', 'Đỗ Thị Hoa', 'User'),
('User_211', 'Nam364', 'TranVanNam@gmail.com', 'Trần Văn Nam', 'User'),
('User_212', 'Linh589', 'VuThiLinh@gmail.com', 'Vũ Thị Linh', 'User'),
('User_213', 'Ham813', 'NguyenVanHam@gmail.com', 'Nguyễn Văn Hâm', 'User'),
('User_214', 'Nga276', 'PhamThiNga@gmail.com', 'Phạm Thị Nga', 'User'),
('User_215', 'Son641', 'LeVanSon@gmail.com', 'Lê Văn Sơn', 'User'),
('User_216', 'Huong958', 'TranThiHuong216@gmail.com', 'Trần Thị Hương', 'User'),
('User_217', 'Thanh392', 'VoVanThanh@gmail.com', 'Võ Văn Thành', 'User'),
('User_218', 'Hong174', 'DinhThiHong@gmail.com', 'Đinh Thị Hồng', 'User'),
('User_219', 'Long529', 'NguyenVanLong@gmail.com', 'Nguyễn Văn Long', 'User'),
('User_220', 'Van863', 'PhamThiVan220@gmail.com', 'Phạm Thị Vân', 'User'),
('User_221', 'Binh347', 'TranVanBinh221@gmail.com', 'Trần Văn Bình', 'User'),
('User_222', 'Thu692', 'LeThiThu@gmail.com', 'Lê Thị Thu', 'User'),
('User_223', 'Manh915', 'DoManh223@gmail.com', 'Đỗ Mạnh', 'User'),
('User_224', 'Nhung268', 'NguyenThiNhung@gmail.com', 'Nguyễn Thị Nhung', 'User'),
('User_225', 'Quang573', 'VuVanQuang225@gmail.com', 'Vũ Văn Quang', 'User'),
('User_226', 'Trang841', 'DinhThiTrang@gmail.com', 'Đinh Thị Trang', 'User'),
('User_227', 'Dat396', 'PhamVanDat@gmail.com', 'Phạm Văn Đạt', 'User'),
('User_228', 'Anh752', 'LeThiAnh228@gmail.com', 'Lê Thị Anh', 'User'),
('User_229', 'Dung194', 'NguyenVanDung229@gmail.com', 'Nguyễn Văn Dũng', 'User'),
('User_230', 'Hanh638', 'VoThiHanh@gmail.com', 'Võ Thị Hạnh', 'User'),
('User_231', 'Vinh927', 'DinhVanVinh@gmail.com', 'Đinh Văn Vinh', 'User'),
('User_232', 'My483', 'TranThiMy@gmail.com', 'Trần Thị Mỹ', 'User'),
('User_233', 'Trung715', 'NguyenVanTrung@gmail.com', 'Nguyễn Văn Trung', 'User'),
('User_234', 'Chi269', 'LeThiChi@gmail.com', 'Lê Thị Chi', 'User'),
('User_235', 'Hoang584', 'PhamVanHoang@gmail.com', 'Phạm Văn Hoàng', 'User'),
('User_236', 'Yen831', 'TranThiYen236@gmail.com', 'Trần Thị Yến', 'User'),
('User_237', 'Tien376', 'VuVanTien@gmail.com', 'Vũ Văn Tiến', 'User'),
('User_238', 'Phuong692', 'NguyenThiPhuong@gmail.com', 'Nguyễn Thị Phương', 'User'),
('User_239', 'Quan145', 'DoVanQuan@gmail.com', 'Đỗ Văn Quân', 'User'),
('User_240', 'Bich528', 'TranThiBich240@gmail.com', 'Trần Thị Bích', 'User'),
('User_241', 'Hai973', 'NhiVanHai@gmail.com', 'Nhị Văn Hải', 'User'),
('User_242', 'Huyen316', 'DucThiHuyen@gmail.com', 'Đức Thị Huyền', 'User'),
('User_243', 'Cuong684', 'NguyenVanCuong243@gmail.com', 'Nguyễn Văn Cường', 'User'),
('User_244', 'Giang927', 'VoThiGiang@gmail.com', 'Võ Thị Giang', 'User'),
('User_245', 'Phong452', 'TranVanHuu@gmail.com', 'Trần Văn Hữu', 'User'),
('User_246', 'Tuyet789', 'PhamThiTuyet246@gmail.com', 'Phạm Thị Tuyết', 'User'),
('User_247', 'Diep263', 'NguyenThiDiep@gmail.com', 'Nguyễn Thị Diệp', 'User'),
('User_248', 'Quoc591', 'LeQuoc248@gmail.com', 'Lê Quốc', 'User'),
('User_249', 'Nhu847', 'TranThiNhu249@gmail.com', 'Trần Thị Như', 'User'),
('User_250', 'Loan392', 'VoThiLoan@gmail.com', 'Võ Thị Loan', 'User'),
('User_251', 'Khanh675', 'NguyenGiaKhanh@gmail.com', 'Nguyễn Gia Khánh', 'User'),
('User_252', 'Truong128', 'PhamVanTruong@gmail.com', 'Phạm Văn Trường', 'User'),
('User_253', 'Thao493', 'LeThiThao253@gmail.com', 'Lê Thị Thảo', 'User'),
('User_254', 'Hien756', 'VuThiHien@gmail.com', 'Vũ Thị Hiền', 'User'),
('User_255', 'An294', 'TranVanAn@gmail.com', 'Trần Văn An', 'User'),
('User_256', 'Lien583', 'NguyenThiLien@gmail.com', 'Nguyễn Thị Liên', 'User'),
('User_257', 'Danh847', 'PhamVanDanh257@gmail.com', 'Phạm Văn Danh', 'User'),
('User_258', 'Hau392', 'LeThiHau@gmail.com', 'Lê Thị Hậu', 'User'),
('User_259', 'Tri675', 'NguyenTri259@gmail.com', 'Nguyễn Trí', 'User'),
('User_260', 'Kim128', 'TranThiKim@gmail.com', 'Trần Thị Kim', 'User'),
('User_261', 'Tho493', 'PhamVanTho@gmail.com', 'Phạm Văn Thọ', 'User'),
('User_262', 'Chau756', 'DoThiChau@gmail.com', 'Đỗ Thị Châu', 'User'),
('User_263', 'Duy294', 'VuVanDuy@gmail.com', 'Vũ Văn Duy', 'User'),
('User_264', 'Xuan583', 'NguyenThiXuan@gmail.com', 'Nguyễn Thị Xuân', 'User'),
('User_265', 'Thinh847', 'LeVanThinh@gmail.com', 'Lê Văn Thịnh', 'User'),
('User_266', 'Ly392', 'TranThiLy@gmail.com', 'Trần Thị Ly', 'User'),
('User_267', 'Nghia675', 'PhamVanNghia@gmail.com', 'Phạm Văn Nghĩa', 'User'),
('User_268', 'Diem128', 'VoThiDiem@gmail.com', 'Võ Thị Diễm', 'User'),
('User_269', 'Khoa493', 'NguyenKhoa@gmail.com', 'Nguyễn Khoa', 'User'),
('User_270', 'Suong756', 'TranThiSuong@gmail.com', 'Trần Thị Sương', 'User'),
('User_271', 'Cong294', 'PhamVanCong271@gmail.com', 'Phạm Văn Công', 'User'),
('User_272', 'Ha583', 'TranThiHa@gmail.com', 'Trần Thị Hà', 'User'),
('User_273', 'Lam847', 'LeVanLam@gmail.com', 'Lê Văn Lâm', 'User'),
('User_274', 'Hien392', 'VoThiHien@gmail.com', 'Võ Thị Hiên', 'User'),
('User_275', 'Phu675', 'NguyenVanPhu@gmail.com', 'Nguyễn Văn Phú', 'User'),
('User_276', 'Cam128', 'PhamThiCam276@gmail.com', 'Phạm Thị Cẩm', 'User'),
('User_277', 'Dang493', 'LeVanDang@gmail.com', 'Lê Văn Đăng', 'User'),
('User_278', 'Trinh756', 'NguyenThiTrinh@gmail.com', 'Nguyễn Thị Trinh', 'User'),
('User_279', 'Duan294', 'TranDuan@gmail.com', 'Trần Duẩn', 'User'),
('User_280', 'Le583', 'VuThiLe280@gmail.com', 'Vũ Thị Lệ', 'User'),
('User_281', 'Luan847', 'PhamVanLuan@gmail.com', 'Phạm Văn Luân', 'User'),
('User_282', 'Hang392', 'NguyenThiHang@gmail.com', 'Nguyễn Thị Hằng', 'User'),
('User_283', 'Sinh675', 'LeVanSinh283@gmail.com', 'Lê Văn Sinh', 'User'),
('User_284', 'Hue128', 'TranThiHue@gmail.com', 'Trần Thị Huệ', 'User'),
('User_285', 'Quy493', 'PhamVanQuy285@gmail.com', 'Phạm Văn Quý', 'User'),
('User_286', 'Dong756', 'NguyenVanDong@gmail.com', 'Nguyễn Văn Đông', 'User'),
('User_287', 'Bach294', 'TranThiBach287@gmail.com', 'Trần Thị Bạch', 'User'),
('User_288', 'Vu583', 'LeVanVu@gmail.com', 'Lê Văn Vũ', 'User'),
('User_289', 'Oanh847', 'PhamThiOanh@gmail.com', 'Phạm Thị Oanh', 'User'),
('User_290', 'Loc392', 'NguyenVanLoc@gmail.com', 'Nguyễn Văn Lộc', 'User'),
('User_291', 'Tam675', 'TranThiTam@gmail.com', 'Trần Thị Tâm', 'User'),
('User_292', 'Can128', 'LeVanCan@gmail.com', 'Lê Văn Cần', 'User'),
('User_293', 'Tien493', 'VuThiTien@gmail.com', 'Vũ Thị Tiên', 'User'),
('User_294', 'Trong756', 'PhamVanTrong@gmail.com', 'Phạm Văn Trọng', 'User'),
('User_295', 'Uyen294', 'TranThiUyen@gmail.com', 'Trần Thị Uyên', 'User'),
('User_296', 'Ung583', 'NguyenVanUng@gmail.com', 'Nguyễn Văn Ưng', 'User'),
('User_297', 'Quyen847', 'LeThiQuyen@gmail.com', 'Lê Thị Quyên', 'User'),
('User_298', 'Hiep392', 'PhamVanHiep@gmail.com', 'Phạm Văn Hiệp', 'User'),
('User_299', 'Chung675', 'TranThiChung@gmail.com', 'Trần Thị Chung', 'User'),
('User_300', 'Thai128', 'NguyenVanThai@gmail.com', 'Nguyễn Văn Thái', 'User'),
('User_301', 'Quynh493', 'TranThiQuynh301@gmail.com', 'Trần Thị Quỳnh', 'User'),
('User_302', 'Khoi756', 'LeVanKhoi@gmail.com', 'Lê Văn Khôi', 'User'),
('User_303', 'Thuy294', 'PhamThiThuy@gmail.com', 'Phạm Thị Thúy', 'User'),
('User_304', 'Ba583', 'NguyenVanBa304@gmail.com', 'Nguyễn Văn Ba', 'User'),
('User_305', 'Vy847', 'LeThiVy@gmail.com', 'Lê Thị Vy', 'User'),
('User_306', 'Tu392', 'TranVanTu306@gmail.com', 'Trần Văn Tú', 'User'),
('User_307', 'Ngoc675', 'PhamThiNgoc307@gmail.com', 'Phạm Thị Ngọc', 'User'),
('User_308', 'Minh128', 'NguyenMinh308@gmail.com', 'Nguyễn Minh', 'User'),
('User_309', 'Luu493', 'TranVanLuu@gmail.com', 'Trần Văn Lưu', 'User'),
('User_310', 'Ngan756', 'LeThiNgan310@gmail.com', 'Lê Thị Ngân', 'User'),
('User_311', 'Phat294', 'NguyenPhat@gmail.com', 'Nguyễn Phát', 'User'),
('User_312', 'Hoa583', 'TranThiHoa312@gmail.com', 'Trần Thị Hoa', 'User'),
('User_313', 'Dan847', 'PhamDan313@gmail.com', 'Phạm Đan', 'User'),
('User_314', 'Thuy392', 'NguyenThuy314@gmail.com', 'Nguyễn Thúy', 'User'),
('User_315', 'Bao675', 'LeBao@gmail.com', 'Lê Bảo', 'User'),
('User_316', 'My128', 'TranThiMy316@gmail.com', 'Trần Thị Mỹ', 'User'),
('User_317', 'Thang493', 'PhamThang@gmail.com', 'Phạm Thắng', 'User'),
('User_318', 'Hieu756', 'NguyenHieu318@gmail.com', 'Nguyễn Hiếu', 'User'),
('User_319', 'Xuan294', 'LeXuan@gmail.com', 'Lê Xuân', 'User'),
('User_320', 'Nhi583', 'TranThiNhi320@gmail.com', 'Trần Thị Nhi', 'User'),
('User_321', 'Sang847', 'PhamVanSang@gmail.com', 'Phạm Văn Sang', 'User'),
('User_322', 'Trinh392', 'NguyenThiTrinh322@gmail.com', 'Nguyễn Thị Trinh', 'User'),
('User_323', 'Si675', 'NguyenVanSi323@gmail.com', 'Nguyễn Văn Sĩ', 'User'),
('User_324', 'Thanh128', 'TranThiThanh@gmail.com', 'Trần Thị Thanh', 'User'),
('User_325', 'Loc493', 'TrinhVanLoc325@gmail.com', 'Trịnh Văn Lộc', 'User'),
('User_326', 'Huyen756', 'LeThiHuyen@gmail.com', 'Lê Thị Huyền', 'User'),
('User_327', 'Tham294', 'NguyenVanTham@gmail.com', 'Nguyễn Văn Thắm', 'User'),
('User_328', 'Hanh583', 'PhamThiHanh@gmail.com', 'Phạm Thị Hạnh', 'User'),
('User_329', 'Duong847', 'TranVanDuong329@gmail.com', 'Trần Văn Dương', 'User'),
('User_330', 'Tuyen392', 'LeThiTuyen@gmail.com', 'Lê Thị Tuyền', 'User'),
('User_331', 'Quyen675', 'TranVanQuyen331@gmail.com', 'Trần Văn Quyến', 'User'),
('User_332', 'Oanh128', 'NguyenThiOanh@gmail.com', 'Nguyễn Thị Oanh', 'User'),
('User_333', 'Dong493', 'PhamVanDong@gmail.com', 'Phạm Văn Đông', 'User'),
('User_334', 'Hanh756', 'LeThiHanh334@gmail.com', 'Lê Thị Hạnh', 'User'),
('User_335', 'Vinh294', 'NguyenVanVinh@gmail.com', 'Nguyễn Văn Vinh', 'User'),
('User_336', 'Thu583', 'TranThiThu336@gmail.com', 'Trần Thị Thu', 'User'),
('User_337', 'Bang847', 'PhamVanBang@gmail.com', 'Phạm Văn Bằng', 'User'),
('User_338', 'Lien392', 'LeThiLien338@gmail.com', 'Lê Thị Liên', 'User'),
('User_339', 'Ky675', 'NguyenVanKy@gmail.com', 'Nguyen Văn Kỳ', 'User'),
('User_340', 'Tuong128', 'TranTuong@gmail.com', 'Trần Tường', 'User'),
('User_341', 'Cam493', 'LeThiCam@gmail.com', 'Lê Thị Cẩm', 'User'),
('User_342', 'Duong756', 'PhamDuong@gmail.com', 'Phạm Dương', 'User'),
('User_343', 'Nguyet294', 'NguyenThiNguyet@gmail.com', 'Nguyễn Thị Nguyệt', 'User'),
('User_344', 'Phung583', 'TranPhung@gmail.com', 'Trần Phụng', 'User'),
('User_345', 'Nhan847', 'LeNhan@gmail.com', 'Lê Nhàn', 'User'),
('User_346', 'Kien392', 'NguyenKien@gmail.com', 'Nguyễn Kiên', 'User'),
('User_347', 'Phi675', 'PhamPhi347@gmail.com', 'Phạm Phi', 'User'),
('User_348', 'Huong128', 'LeThiHuong@gmail.com', 'Lê Thị Hương', 'User'),
('User_349', 'Tra493', 'NguyenTra@gmail.com', 'Nguyễn Trà', 'User'),
('User_350', 'Tram756', 'TranThiTram@gmail.com', 'Trần Thị Trâm', 'User'),
('User_351', 'Hoai294', 'PhamHoai@gmail.com', 'Phạm Hoài', 'User'),
('User_352', 'Bao583', 'NguyenBao352@gmail.com', 'Nguyễn Bảo', 'User'),
('User_353', 'Viet847', 'LeViet@gmail.com', 'Lê Việt', 'User'),
('User_354', 'Yen392', 'NguyenThiYen@gmail.com', 'Nguyễn Thị Yến', 'User'),
('User_355', 'Phuc675', 'TranPhuc@gmail.com', 'Trần Phúc', 'User'),
('User_356', 'Ly128', 'LeThiLy356@gmail.com', 'Lê Thị Ly', 'User'),
('User_357', 'Hau493', 'NguyenHau@gmail.com', 'Nguyễn Hậu', 'User'),
('User_358', 'My756', 'PhamThiMy@gmail.com', 'Phạm Thị Mỹ', 'User'),
('User_359', 'Tu294', 'TranTu359@gmail.com', 'Trần Tú', 'User'),
('User_360', 'Chau583', 'LeThiChau360@gmail.com', 'Lê Thị Châu', 'User'),
('User_361', 'Hung847', 'NguyenVanHung361@gmail.com', 'Nguyễn Văn Hùng', 'User'),
('User_362', 'Lan392', 'TranThiLan@gmail.com', 'Trần Thị Lan', 'User'),
('User_363', 'Minh675', 'PhamVanMinh363@gmail.com', 'Phạm Văn Minh', 'User'),
('User_364', 'Hoa128', 'NguyenThiHoa364@gmail.com', 'Nguyễn Thị Hoa', 'User'),
('User_365', 'Nam493', 'LeVanNam@gmail.com', 'Lê Văn Nam', 'User'),
('User_366', 'Linh756', 'TranThiLinh366@gmail.com', 'Trần Thị Linh', 'User'),
('User_367', 'Duc294', 'NguyenVanDuc@gmail.com', 'Nguyễn Văn Đức', 'User'),
('User_368', 'Nga583', 'PhamThiNga368@gmail.com', 'Phạm Thị Nga', 'User'),
('User_369', 'Son847', 'LeVanSon369@gmail.com', 'Lê Văn Sơn', 'User'),
('User_370', 'Huong392', 'NguyenThiHuong@gmail.com', 'Nguyễn Thị Hương', 'User'),
('User_371', 'Thanh675', 'VoVanThanh371@gmail.com', 'Võ Văn Thành', 'User'),
('User_372', 'Hong128', 'TranThiHong@gmail.com', 'Trần Thị Hồng', 'User'),
('User_373', 'Long493', 'PhamVanLong@gmail.com', 'Phạm Văn Long', 'User'),
('User_374', 'Van756', 'NguyenThiVan374@gmail.com', 'Nguyễn Thị Vân', 'User'),
('User_375', 'Binh294', 'TranVanBinh375@gmail.com', 'Trần Văn Bình', 'User'),
('User_376', 'Thu583', 'LeThiThu376@gmail.com', 'Lê Thị Thu', 'User'),
('User_377', 'Manh847', 'NguyenManh@gmail.com', 'Nguyễn Mạnh', 'User'),
('User_378', 'Nhung392', 'TranThiNhung@gmail.com', 'Trần Thị Nhung', 'User'),
('User_379', 'Quang675', 'PhamVanQuang@gmail.com', 'Phạm Văn Quang', 'User'),
('User_380', 'Trang128', 'LeThiTrang@gmail.com', 'Lê Thị Trang', 'User'),
('User_381', 'Dat493', 'NguyenVanDat@gmail.com', 'Nguyễn Văn Đạt', 'User'),
('User_382', 'Anh756', 'TranThiAnh@gmail.com', 'Trần Thị Anh', 'User'),
('User_383', 'Dung294', 'LeVanDung@gmail.com', 'Lê Văn Dũng', 'User'),
('User_384', 'Hanh583', 'NguyenThiHanh384@gmail.com', 'Nguyễn Thị Hạnh', 'User'),
('User_385', 'Vinh847', 'PhamVanVinh385@gmail.com', 'Phạm Văn Vinh', 'User'),
('User_386', 'My392', 'TranThiMy386@gmail.com', 'Trần Thị Mỹ', 'User'),
('User_387', 'Trung675', 'NguyenVanTrung387@gmail.com', 'Nguyễn Văn Trung', 'User'),
('User_388', 'Chi128', 'LeThiChi388@gmail.com', 'Lê Thị Chi', 'User'),
('User_389', 'Hoang493', 'TranVanHoang@gmail.com', 'Trần Văn Hoàng', 'User'),
('User_390', 'Yen756', 'PhamThiYen@gmail.com', 'Phạm Thị Yến', 'User'),
('User_391', 'Tien294', 'NguyenVanTien391@gmail.com', 'Nguyễn Văn Tiến', 'User'),
('User_392', 'Phuong583', 'TranThiPhuong392@gmail.com', 'Trần Thị Phương', 'User'),
('User_393', 'Quan847', 'LeVanQuan@gmail.com', 'Lê Văn Quân', 'User'),
('User_394', 'Bich392', 'NguyenThiBich@gmail.com', 'Nguyễn Thị Bích', 'User'),
('User_395', 'Hai675', 'PhamVanHai@gmail.com', 'Phạm Văn Hải', 'User'),
('User_396', 'Huyen128', 'TranThiHuyen396@gmail.com', 'Trần Thị Huyền', 'User'),
('User_397', 'Cuong493', 'NguyenVanCuong397@gmail.com', 'Nguyễn Văn Cường', 'User'),
('User_398', 'Giang756', 'PhamThiGiang@gmail.com', 'Phạm Thị Giang', 'User'),
('User_399', 'Ling294', 'TranVanLing@gmail.com', 'Trần Văn Ling', 'User'),
('User_400', 'Tuyet583', 'NguyenThiTuyet@gmail.com', 'Nguyễn Thị Tuyết', 'User');

select* from Users;

-- BẢNG 2: ChildProfiles - Quản lý hồ sơ trẻ em
CREATE TABLE ChildProfiles (
  ChildID INT PRIMARY KEY AUTO_INCREMENT,  -- ID hồ sơ trẻ, tự động tăng
  UserID INT NOT NULL,                      -- Chủ sở hữu hồ sơ này (người dùng)
  ChildName VARCHAR(100) NOT NULL,         -- Tên trẻ
  DateOfBirth DATE NOT NULL,               -- Ngày sinh
  Gender ENUM('Male', 'Female') NOT NULL,  -- Giới tính của trẻ
  HeightCm DECIMAL(5,2),                   -- Chiều cao (cm)
  WeightKg DECIMAL(5,2),                   -- Cân nặng (kg)
  BMI DECIMAL(4,2),                        -- Chỉ số BMI
  FOREIGN KEY (UserID) REFERENCES Users(UserID) -- Liên kết với Users để biết hồ sơ này thuộc về ai
);

-- BẢNG 3: Memberships - Quản lý gói thành viên & thanh toán
CREATE TABLE Memberships (
  MembershipID INT PRIMARY KEY AUTO_INCREMENT, -- ID gói thành viên, tự động tăng
  UserID INT NOT NULL UNIQUE,                  -- ID người dùng sở hữu gói này
  MembershipType ENUM('Basic', 'Premium') NOT NULL, -- Loại gói thành viên
  Price DECIMAL(10,2) NOT NULL,                -- Giá tiền của gói
  StartDate DATE NOT NULL,                     -- Ngày bắt đầu
  EndDate DATE NOT NULL,                       -- Ngày hết hạn
  PaymentMethod VARCHAR(50) NOT NULL,          -- Phương thức thanh toán
  TransactionStatus ENUM('Success', 'Failed') NOT NULL, -- Trạng thái thanh toán
  FOREIGN KEY (UserID) REFERENCES Users(UserID) -- Liên kết với Users
);

-- BẢNG 4: Alerts - Quản lý cảnh báo sức khỏe của trẻ
CREATE TABLE Alerts (
  AlertID INT PRIMARY KEY AUTO_INCREMENT, -- ID cảnh báo, tự động tăng
  ChildID INT NOT NULL,                   -- Hồ sơ trẻ nhận cảnh báo
  AlertType VARCHAR(50) NOT NULL,         -- Loại cảnh báo (Sốt, Dị ứng, ...)
  Description TEXT NOT NULL,              -- Mô tả chi tiết
  AlertDate DATETIME DEFAULT CURRENT_TIMESTAMP, -- Ngày tạo cảnh báo
  FOREIGN KEY (ChildID) REFERENCES ChildProfiles(ChildID) -- Liên kết với ChildProfiles
);

-- BẢNG 5: Consultations - Quản lý tư vấn giữa người dùng và bác sĩ
CREATE TABLE Consultations (
  ConsultationID INT PRIMARY KEY AUTO_INCREMENT,  -- ID tư vấn, tự động tăng
  UserID INT NOT NULL,                            -- Người yêu cầu tư vấn
  DoctorID INT NOT NULL,                          -- Bác sĩ tư vấn
  ChildID INT NOT NULL,                           -- Hồ sơ trẻ liên quan
  RequestDate DATETIME DEFAULT CURRENT_TIMESTAMP, -- Ngày yêu cầu tư vấn
  Message TEXT NOT NULL,                          -- Nội dung tư vấn
  Status ENUM('Pending', 'Completed') DEFAULT 'Pending', -- Trạng thái tư vấn
  FeedbackText TEXT,                              -- Nội dung phản hồi từ user
  FeedbackCreatedAt DATETIME,                     -- Thời gian phản hồi
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (DoctorID) REFERENCES Users(UserID),
  FOREIGN KEY (ChildID) REFERENCES ChildProfiles(ChildID)
);

-- BẢNG 6: Reports - Quản lý báo cáo & dashboard
CREATE TABLE Reports (
  ReportID INT PRIMARY KEY AUTO_INCREMENT,    -- ID báo cáo, tự động tăng
  ReportName VARCHAR(100) NOT NULL,           -- Tên báo cáo
  Description TEXT,                           -- Mô tả báo cáo
  GeneratedAt DATETIME DEFAULT CURRENT_TIMESTAMP, -- Ngày tạo báo cáo
  GeneratedByUserID INT NOT NULL,             -- Người tạo báo cáo (Admin)
  ReportData JSON,                            -- Dữ liệu thống kê dạng JSON
  FOREIGN KEY (GeneratedByUserID) REFERENCES Users(UserID) -- Liên kết với Users
);

-- BẢNG 7: ContentPosts - Quản lý Blog & FAQ
CREATE TABLE ContentPosts (
  PostID INT PRIMARY KEY AUTO_INCREMENT,  -- ID bài viết, tự động tăng
  Title VARCHAR(255) NOT NULL,            -- Tiêu đề bài viết
  Content TEXT NOT NULL,                  -- Nội dung bài viết
  PostType ENUM('Blog', 'FAQ') NOT NULL,  -- Loại bài (Blog hoặc FAQ)
  AuthorID INT,                            -- Người viết bài (nếu có)
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, -- Ngày tạo bài viết
  FOREIGN KEY (AuthorID) REFERENCES Users(UserID) -- Liên kết với Users (Admin viết bài)
);