<<<<<<< HEAD
spring.application.name=ChildGrowthSystem
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
spring.application.name=ChildGrowthSystem
=======
>>>>>>> 7dc820a (cập nhật repo và service cho các entity)
spring.application.name=BE
# Cấu hình kết nối MySQL (này ông Đạt điền nha)
spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name
spring.datasource.username=root 	
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 7f20d46 (first commit)
<<<<<<< HEAD
=======
>>>>>>> 78b4918cd3926d771a75a3fbf8d5dff393f594c0
>>>>>>> 7dc820a (cập nhật repo và service cho các entity)
